2024-10-01 14:25:09,940 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\WED\PycharmProjects\Lesson_12\tests_12_4.py", line 27, in test_run
    bob = rt_new.Runner([1, 2, 3], 10)
  File "C:\Users\WED\PycharmProjects\Lesson_12\runner_and_tournament_new.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано list
2024-10-01 14:25:09,942 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\WED\PycharmProjects\Lesson_12\tests_12_4.py", line 14, in test_walk
    jhon = rt_new.Runner('Jhon', -5)
  File "C:\Users\WED\PycharmProjects\Lesson_12\runner_and_tournament_new.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
